hannesmannerheim/qvitter

actions/apiqvitternotifications.php

Various code style fixes to align with the rest of GNU social, as well as some maybe-performance-enhancements (only sending changed keys to SQL db as well as not iterating the same array twice).

Qvitter notification code style

---

classes/QvitterNotification.php

This was causing:
PHP Notice:  Undefined property: QvitterNotification::$is_seen in /srv/www/vhosts/quitter.es/%/htdocs/local/plugins/Qvitter/actions/apiqvitternotifications.php on line 115
...better match them to each other :]

Class var declarations did not match SQL table

---

js/qvitter.js

I guess this is a residual line from when quitter.se had to rewrite their calls to http manually?

Don't replace https with http in form action URL

---

js/qvitter.js

Fix a glitch in css style for background

Bug on image background URL

---

QvitterPlugin.php
README.md
actions/qvitter.php
js/lan.js

Added a config.php parameter and its usage to be able to use an alternative favicon.ico

External parameter for favicon.ico

---

actions/qvitter.php

Fixes https://github.com/hannesmannerheim/qvitter/issues/98

Local group and group feed fixes

---

actions/apiexternalusershow.php

I've had problems when clicking the profile name of for example @erkan@fediverse.com when running PHP 5.6 since 5.6 has implemented other defaults for TLS certificate checking. The 'file_get_contents' and 'get_headers' calls uses PHP stream contexts which hadn't been configured with config.php, so I made the calls use HTTPClient instead, which is used everywhere else in GNU social (and thus has a consistent TLS policy across the entire backend).
Commit message:
The GNU social node has configured HTTPClient (HTTP_Request2 object) with
certain characteristics, which won't be respected when just using the PHP
built-in fetchers. This way we can have the same TLS certificate policy,
timeouts etc.
Also removed one test if get_headers() had returned an array, which it
never will since the …

Use GNU social HTTPClient to GET and HEAD (consistent HTTP config)

---

actions/qvitter.php

Use getActivePlugins() list to see if OpenID is active

---

js/dom-functions.js

The previous one was too hastily copy-pasted from the image-expanding part... Sorry. :)

Test against an element that actually will exist

---

js/misc-functions.js

Checking obj.background_image for undefined.

Fixed issue #175

---

QvitterPlugin.php

It was impossible to request classic view for profiles if qvitter was enabledbydefault  :)

$logged_in_user was changed to $scoped before

---

QvitterPlugin.php

The last change, which uses self::makeRegex, is to get rid of STRICT STANDARDS warnings (which I tried with the "crazy stunt" thing before, but this should be less controversial :))

Minor fixes

---

locale/ido.json

Third Ido revision

---

locale/ido.json

Few corrections, translation of "Click to drag".

Tenth Ido translation

---

QvitterPlugin.php

there's strict type comparison later on (===, three equals) for true and false

Don't examplify with a string boolean

---

doc/no/shortcuts.html
doc/no/terms.html

Added shortcuts file to the norwegian doc folder

Added shortcuts to NO doc

---

doc/no/shortcuts.html

Changed some of the translations

Changed some of the translations in shortcuts

---

locale/no.json

Updated norwegian translation

---

doc/en/faq.html

see the change notes for further information

changes to the FAQ regarding Twidere and remote folllow

---

QvitterPlugin.php
js/dom-functions.js
js/misc-functions.js

I think this solves https://git.gnu.io/gnu/gnu-social/issues/112

Change 'is_activity' to the inverse, 'is_post_verb'
